[build]  
  publish = "dist"

[[redirects]]
    from = "/prefetch"
    to = "/prefetch/index.html"
    status = 200

  [[redirects]]
    from = "/prerender"
    to = "/prerender/index.html"
    status = 200